@startuml Sprint2_CasUtilisation_Global
title Diagramme de Cas d'Utilisation — Sprint 2 FormaPro

left to right direction
skinparam packageStyle rectangle
skinparam actorStyle awesome

actor "Formateur" as F
actor "Administrateur" as ADMIN

rectangle "FormaPro — Sprint 2 : Gestion des formations" {
    usecase "Créer une formation (draft)" as UC1
    usecase "Modifier une formation (draft)" as UC2
    usecase "Supprimer une formation" as UC3
    usecase "Gérer les modules" as UC4
    usecase "Gérer le programme pédagogique" as UC5
    usecase "Gérer les séances" as UC6
    usecase "Uploader des supports pédagogiques" as UC7
    usecase "Soumettre à l'approbation" as UC8
    usecase "Créer/modifier une formation (Admin)" as UC9
    usecase "Accepter une formation" as UC10
    usecase "Rejeter une formation" as UC11
    usecase "Publier une formation" as UC12
    usecase "Consulter toutes les formations" as UC13
}

F --> UC1
F --> UC2
F --> UC3
F --> UC4
F --> UC5
F --> UC6
F --> UC7
F --> UC8

ADMIN --> UC9
ADMIN --> UC10
ADMIN --> UC11
ADMIN --> UC12
ADMIN --> UC13

UC2 .> UC1 : <<extend>>
UC4 .> UC1 : <<extend>>
UC5 .> UC1 : <<extend>>
UC6 .> UC1 : <<extend>>
UC7 .> UC1 : <<extend>>
UC8 .> UC4 : <<include>>
UC12 .> UC10 : <<include>>

@enduml
