@startuml Sprint1_CasUtilisation_Utilisateur
title Diagramme de cas d'utilisation — Utilisateur (Candidat ISET / Formateur / Externe)

left to right direction

scale 0.7
skinparam dpi 150
skinparam actorStyle default
skinparam defaultFontName Arial
skinparam defaultFontSize 12
skinparam nodesep 20
skinparam ranksep 25

skinparam usecase {
    BackgroundColor White
    BorderColor Black
    FontColor Black
}
skinparam actor {
    BackgroundColor White
    BorderColor Black
    FontColor Black
}

actor "Candidat ISET" as CISET
actor "Utilisateur externe" as EXT
actor "Formateur" as F

usecase "S'inscrire" as UC1
usecase "S'inscrire (Candidat ISET)" as UC1_1
usecase "S'inscrire (Utilisateur externe)" as UC1_2
usecase "S'authentifier" as UC2
usecase "Réinitialiser le mot de passe" as UC3

CISET -- UC1
EXT   -- UC1
CISET -- UC3
EXT   -- UC3
F     -- UC3

UC1 ..> UC2 : <<include>>
UC3 ..> UC2 : <<include>>

UC1_1 ..> UC1 : <<extend>>
UC1_2 ..> UC1 : <<extend>>

@enduml
